apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-355616
  artifacts:
    - image: eu.gcr.io/ticketing-dev-355616/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - "src/**/*.ts"
